/*
 * Project name:
     MyProject_TA.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     14/06/2023
 * Test configuration:
     MCU:             STM32F746ZG
     Dev.Board:       Mikromedia_7_Capacitive_STM32
     Oscillator:      216000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "MyProject_TA_objects.h"
extern void systemInit();
extern void applicationInit();

void main() {

  Start_TP();

  systemInit();
  applicationInit();
}